[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
healthcheckPath = "/a"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"

[[services]]
name = "fooder"

[[services.volumes]]
mountPath = "/data"
