export const CUISINES = [
  { id: 'pizza', name: 'Pizza', emoji: '🍕' },
  { id: 'thai', name: 'Thai', emoji: '🍜' },
  { id: 'sushi', name: 'Sushi', emoji: '🍣' },
  { id: 'burgers', name: 'Burgers', emoji: '🍔' },
  { id: 'mexican', name: 'Mexican', emoji: '🌮' },
  { id: 'indian', name: 'Indian', emoji: '🍛' },
  { id: 'chinese', name: 'Chinese', emoji: '🥡' },
  { id: 'mediterranean', name: 'Mediterranean', emoji: '🥙' },
  { id: 'korean', name: 'Korean', emoji: '🥘' },
  { id: 'vietnamese', name: 'Vietnamese', emoji: '🍲' },
  { id: 'ramen', name: 'Ramen', emoji: '🍥' },
  { id: 'italian', name: 'Italian', emoji: '🍝' },
  { id: 'bbq', name: 'BBQ', emoji: '🍖' },
  { id: 'sandwiches', name: 'Sandwiches', emoji: '🥪' },
  { id: 'salad', name: 'Salad', emoji: '🥗' },
];
